name: eCommerce
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
      VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      JWT_ACCESS_TOKEN: ${{secrets.JWT_ACCESS_TOKEN}}
      RAZORPAY_SECRET: ${{secrets.RAZORPAY_SECRET}}
      RAZORPAY_KEY_ID: ${{secrets.RAZORPAY_KEY_ID}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: cd client && npm install
      - name: build frontend project
        run: cd client && npm run build
      - name: frontend build
        run: echo "successfull"
      - name: installing server dependencies
        run: cd server && npm install
      - name: seting up vercel env
        run: |
          cd server
          mkdir .vercel
          cd .vercel
          touch project.json
          echo "{\"orgId\":\"$VERCEL_ORG_ID\",\"projectId\":\"$VERCEL_PROJECT_ID\"}"
        run: |
          cd server && vercel --prod --token=$VERCEL_TOKEN
      - name: project deployed
        run: echo "successfull"

