name: eCommerce
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: cd client && npm install
      - name: build frontend project
        run: cd client && npm run build
      - name: frontend build
        run: echo "successfull"
      - name: installing server dependencies
        run: cd server && npm install
      - name: deploying project
        env:
          VERCEL_ORG_ID: NwYqIbJqU8sccogCaKf0XDdI
          VERCEL_PROJECT_ID: prj_2w3M4whu4aQNv8N1VOaTWEtmIERS
          MONGODB_URI: mongodb+srv://valay:qt3xvYK8H0Hy0nFG@cluster0.mcpjvb5.mongodb.net/test
          JWT_ACCESS_TOKEN: 2a50670925ee66d1e6808254dbf551bc8fec8d6beaa53a5091a79b4d3f33e17013bbd932d6d686380c4677444ac3b4a2aaf2672e596013c72e63a916500491ac
          RAZORPAY_SECRET: wYzbh51mFVQKx1AoX1mQ4B4Z
          RAZORPAY_KEY_ID: rzp_test_SWVOO1lUyi4oSC
        run: cd server && npm run deploy
      - name: project deployed
        run: echo "successfull"

