name: eCommerce
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: cd client && npm install
      - name: build frontend project
        run: cd client && npm run build
      - name: frontend build
        run: echo "successfull"
        run: tree
      - name: deploying project
        env:
          MONGODB_URI: mongodb+srv://vercel-admin-user-634b5072b9e9de6636662e8e:Ffn3CeBTUZh11FNX@cluster0.mcpjvb5.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
          JWT_ACCESS_TOKEN: 2a50670925ee66d1e6808254dbf551bc8fec8d6beaa53a5091a79b4d3f33e17013bbd932d6d686380c4677444ac3b4a2aaf2672e596013c72e63a916500491ac
          RAZORPAY_SECRET: wYzbh51mFVQKx1AoX1mQ4B4Z
          RAZORPAY_KEY_ID: rzp_test_SWVOO1lUyi4oSC
        run: cd server && npm install
        run: cd server && npm run deploy
      - name: project deployed
        run: echo "successfull"

